### ISSUE TITLE
渡辺さんへ

### ISSUE THREAD

**Issue by KimoriTama** [wtnbgo/psdfile#4]
こんにちは，渡辺さん。「psdfile」と「psbfile」の違いがわからず、誤って入ってしまいました。それについては、何どぞ気にしないでください。

でも、貴社がKAGの指令システムを接管するために使用される「world」プラグインに興味があるようですね。envupdateコマンドを使用して、すべてのシーン情報を処理することができます。しかし、「psdfile.dll」で解析できる「PSBFile」クラスのファイルを生成する方法がわからないようですね。私はこの問題について詳しく知りませんです。

もし有用な情報を提供していただけるのであれば、大変感謝いたします。

**Comment by wtnbgo** [comment]
このプラグインは  adobe photoshop のファイルを読み込むためのプラグインです。
一部のゲームタイトルで使われてるpsbファイルとこのプラグインは無関係で、そちらの仕様は公開される予定はありません。
